Architecture changes (#10)
* Big architecture changes

* Some typo fix

* step 2

* Turn to work state

* Rename utils files

* Big architecture changes.

Got first try to implement TIME arrays and matrix.
They were hidden under preprocessor for improvment in the future.

Implemented a memory allocation function with a global variable
switch for easy handling of memory allocation errors.

First steps to expanding the classes of task to be solved.

* Update grid.h

---------

Co-authored-by: v.pogosyan <v.pogosyan@postgresql.ru>

diff --git a/tests/test_default b/tests/test_default
--- a/tests/test_default
+++ b/tests/test_default
@@ -13,7 +13,7 @@ result=$?
 if [ ${result} -ne 0 ]
 then
     echo "ERROR: the program returned a non-zero execution code."
-    exit 2
+    exit ${result}
 fi
 
 sleep 1
@@ -26,6 +26,7 @@ fi
 
 if ls ${DATADIR} | grep 'nan' 
 then
-    echo "ERROR: the write NAN data.";
+    echo "ERROR: were written NAN data.";
     exit 2
 fi
+
