Revert "Architecture changes (#10)" (#11)
This reverts commit 663e65a4b1ab8a383e718558a5bf404f42669628.

diff --git a/tests/test_default b/tests/test_default
--- a/tests/test_default
+++ b/tests/test_default
@@ -13,7 +13,7 @@ result=$?
 if [ ${result} -ne 0 ]
 then
     echo "ERROR: the program returned a non-zero execution code."
-    exit ${result}
+    exit 2
 fi
 
 sleep 1
@@ -26,7 +26,6 @@ fi
 
 if ls ${DATADIR} | grep 'nan' 
 then
-    echo "ERROR: were written NAN data.";
+    echo "ERROR: the write NAN data.";
     exit 2
 fi
-
